/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.108
 * Generated at: 2021-05-25 16:46:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.User;
import com.model.Livre;
import java.util.List;
import com.dao.LivreDao;

public final class Ajouterlivre_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


LivreDao lm=new LivreDao();

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

User u=(User)session.getAttribute("user");

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "sidebar.jsp", out, false);
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("    \n");
      out.write("      <!-- Content Wrapper. Contains page content -->\n");
      out.write("      <div class=\"content-wrapper\">\n");
      out.write("        <!-- Content Header (Page header) -->\n");
      out.write("        <section class=\"content-header\">\n");
      out.write("          <h1>\n");
      out.write("            Livres\n");
      out.write("            <small>Optional description</small>\n");
      out.write("          </h1>\n");
      out.write("          <ol class=\"breadcrumb\">\n");
      out.write("            <li><a href=\"#\"><i class=\"fa fa-dashboard\"></i> Level</a></li>\n");
      out.write("            <li class=\"active\">Here</li>\n");
      out.write("          </ol>\n");
      out.write("        </section>\n");


int id=0;
String auteur="";
String editeur="";
String titre="";
String description="";
String categorie="";
String action="Ajouter";

if(request.getParameter("op")!=null)
{
	if(request.getParameter("op").equals("edit"))
	{
		id= Integer.parseInt(request.getParameter("id"));
		com.model.Livre l=lm.findLivreById(id);
		auteur=l.getAuteur();
		editeur=l.getEditeur();
		titre=l.getTitre();
		description=l.getDescription();
		categorie=l.getCategorie();
		action="Modifier";
		
	}
}

      out.write("\n");
      out.write("        <!-- Main content -->\n");
      out.write("        <section class=\"content\">\n");
      out.write("\n");
      out.write("          <!-- Your Page Content Here -->\n");
      out.write("         \n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t<div class=\"box box-info\">\n");
      out.write("                <div class=\"box-header with-border\">\n");
      out.write("                  <h3 class=\"box-title\">Gestion des livres</h3>\n");
      out.write("                </div><!-- /.box-header -->\n");
      out.write("                <!-- form start -->\n");
      out.write("                <form class=\"form-horizontal\" action=\"serve1\" method=\"post\">\n");
      out.write("                  <div class=\"box-body\">\n");
      out.write("                  <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-sm-2 control-label\">Id</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"number\" readonly=\"readonly\" value=\"");
      out.print(id );
      out.write("\" name=\"id\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"Password\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputEmail3\" class=\"col-sm-2 control-label\">Auteur</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"text\" name=\"auteur\" value=\"");
      out.print(auteur );
      out.write("\" class=\"form-control\" id=\"inputEmail3\" placeholder=\"Auteur\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-sm-2 control-label\">Editeur</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"text\" name=\"editeur\" value=\"");
      out.print(editeur );
      out.write("\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"editeur\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                     <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-sm-2 control-label\">Titre</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"text\" name=\"titre\" value=\"");
      out.print(titre );
      out.write("\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"titre\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                     <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-sm-2 control-label\">Description</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"text\" name=\"description\" value=\"");
      out.print(description );
      out.write("\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"description\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"form-group\">\n");
      out.write("                      <label for=\"inputPassword3\" class=\"col-sm-2 control-label\">Categorie</label>\n");
      out.write("                      <div class=\"col-sm-10\">\n");
      out.write("                        <input type=\"text\" name=\"categorie\" value=\"");
      out.print(categorie );
      out.write("\" class=\"form-control\" id=\"inputPassword3\" placeholder=\"categorie\">\n");
      out.write("                      </div>\n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                  </div><!-- /.box-body -->\n");
      out.write("                  <div class=\"box-footer\">\n");
      out.write("                    <button type=\"reset\" class=\"btn btn-default\">Annuler</button>\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-info pull-right\" name=\"action\" value=\"");
      out.print(action );
      out.write("\">Ajouter</button>\n");
      out.write("                  </div><!-- /.box-footer -->\n");
      out.write("                </form>\n");
      out.write("              </div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("        </section><!-- /.content -->\n");
      out.write("      </div><!-- /.content-wrapper -->\n");
      out.write("\n");
      out.write("      <!-- Main Footer -->\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\n");
      out.write("      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "controlesidebar.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
